FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc pkg-config default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka/ ./kafka/
COPY app/ ./app/
COPY .env.example .env

CMD ["python", "-m", "kafka.consumer.consumer"]